# Generated by Django 3.2 on 2021-09-14 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_auto_20210914_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.PositiveSmallIntegerField(choices=[(1, 'In progress'), (2, 'Completed'), (3, 'Delayed'), (4, 'Pending')], default=1),
        ),
    ]
