# Generated by Django 3.2 on 2021-09-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.CharField(choices=[('In progress', 'In progress'), ('Completed', 'Completed'), ('Delayed', 'Delayed'), ('Pending', 'Pending')], default='In progress', max_length=15),
        ),
    ]
