# Generated by Django 3.2 on 2021-09-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_product_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
