# Generated by Django 3.2 on 2021-09-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0015_auto_20210925_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Camera',
            field=models.CharField(blank=True, choices=[('up to 2.9 MP', 'up to 2.9 MP'), ('3 to 4.9 MP', '3 to 4.9 MP'), ('5 to 7.9 MP', '5 to 7.9 MP'), ('8 to 12.9 MP', '8 to 12.9 MP'), ('13 to 19.9 MP', '13 to 19.9 MP'), ('20 MP and above', '20 MP and above')], max_length=100, null=True),
        ),
    ]
