# Generated by Django 3.2 on 2021-09-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0016_alter_product_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Cam',
            field=models.IntegerField(blank=True, default=15, max_length=100, null=True),
        ),
    ]
