# Generated by Django 3.2 on 2021-09-19 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Pharmacy', '0002_auto_20210914_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Address',
            field=models.CharField(default='El-wiam', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Sex',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Sidi bel-abbes', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='county',
            field=models.CharField(default='Algérie', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
