# Generated by Django 3.2 on 2021-09-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pharmacy', '0005_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Sex',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], max_length=50, null=True),
        ),
    ]
