# Generated by Django 3.2 on 2021-09-24 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0014_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Memory',
            field=models.CharField(blank=True, choices=[('4Go', '4Go'), ('8Go', '8Go'), ('16Go', '16Go'), ('32Go', '32Go'), ('64Go', '64Go'), ('128Go', '128Go'), ('256Go', '256Go'), ('1To', '1To')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='System',
            field=models.CharField(blank=True, choices=[('Android', 'Android'), ('IOS', 'IOS'), ('Fire', 'Fire'), ('Linux', 'Linux'), ('Windows', 'Windows')], max_length=100, null=True),
        ),
    ]
